import os

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import getSampleStyleSheet

REPORT_FOLDER = "reports"


def create_report_folder():

    os.makedirs(
        REPORT_FOLDER,
        exist_ok=True
    )


def generate_transaction_report(
    transaction_id,
    amount,
    time,
    transactions_today,
    is_foreign,
    is_high_risk_country,
    prediction,
    risk_score,
    risk_level,
    recommendation
):

    create_report_folder()

    filename = (
        f"{REPORT_FOLDER}/"
        f"fraud_report_{transaction_id}.pdf"
    )

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    title = Paragraph(
        "Fraud Detection Investigation Report",
        styles["Title"]
    )

    content.append(title)

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            f"<b>Transaction ID:</b> {transaction_id}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Amount:</b> ₹{amount}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Hour:</b> {time}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Transactions Today:</b> {transactions_today}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Foreign Transaction:</b> {is_foreign}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>High Risk Country:</b> {is_high_risk_country}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Prediction:</b> {prediction}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Risk Score:</b> {risk_score}%",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Risk Level:</b> {risk_level}",
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "<b>Recommendation</b>",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            recommendation,
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Generated by Fraud Analytics Platform",
            styles["Italic"]
        )
    )

    doc.build(content)

    return filename